zip_url: https://github.com/LionSpeck/chalk/releases/download/v1.0.2-beta/chalk_v1.0.2-beta.zip
tar_url: https://github.com/LionSpeck/chalk/archive/refs/tags/v1.0.2-beta.tar.gz
show_downloads: true
theme: jekyll-theme-midnight
